[font]
size = 12.0

[font.bold]
family = "JetBrainsMono NFM"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NFM"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NFM"
style = "Italic"

[font.normal]
family = "JetBrainsMono NFM"
style = "Regular"

[terminal]

[terminal.shell]
args = ["--cd ~"]
program = 'C:\Windows\System32\wsl.exe'
