[projects."/Users/rojasfe/Documents/Projects/IonTorrent/IonChef/github/prototypes"]
trust_level = "trusted"

[mcp_servers.dart]
command = "dart"
args = ["mcp-server"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

